[project]
name = "15-08-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.2.7",
    "openai-sdk>=0.1.0",
]
